## fit_transform() 和 np.c_[   ]

In [26]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor

In [45]:
arr_X = np.array(
   [
    [1.5, -1., 2.,5,7],
    [2., 0., 0.5,-1,2]
    ]
  )


X_train,y_train=(
        arr_X[:,:-1],
        arr_X[:,-1],
      )

In [59]:
print(f"raw [shape:{arr_X.shape}]:\n{arr_X}")
print(f"X_train [shape:{X_train.shape}]:\n{X_train}")
print(f"y_train [shape:{y_train.shape}]:\n{y_train}")

raw [shape:(2, 5)]:
[[ 1.5 -1.   2.   5.   7. ]
 [ 2.   0.   0.5 -1.   2. ]]
X_train [shape:(2, 4)]:
[[ 1.5 -1.   2.   5. ]
 [ 2.   0.   0.5 -1. ]]
y_train [shape:(2,)]:
[7. 2.]


In [60]:
arr_X = np.array(
   [
    [1.5, -1., 2.],
    [2., 0., 0.]
    ]
  )
#x_np=pd.DataFrame(arr_np)
#x_np=np.array(df_np)
arr_y=np.array(
  [5,8
    # [5],
    # [8]
  ]
)

rf=RandomForestRegressor(random_state=42)
rf.fit(arr_X,arr_y)
params=rf.get_params()
arr_X.shape,arr_y.shape

((2, 3), (2,))

In [73]:
test_X = np.array(
   [
    [2.5, -5., 1.]
    ]
  )
test_y_pred=rf.predict(test_X)
test_y_pred,type(test_y_pred)

(array([6.8]), numpy.ndarray)

In [74]:
print(test_y_pred)

[6.8]


In [76]:
test_y_pred[0]

6.8

In [36]:
arr_np = np.array(
   [
    [1.5, -1., 2.],
    [2., 0., 0.]
    ]
  )
x_np=pd.DataFrame(arr_np)
#x_np=np.array(df_np)
y_np=np.array(
  [
    [5],
    [8]
  ]
)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_np)

print("arr_np: \n",arr_np)
#print("df_np: \n",df_np)
print("x_np: \n",x_np)
print("y_np: \n",y_np)
print("x_train: \n",x_train)
print("x_train and y_np: \n",np.c_[x_train,y_np])
print("type of x_np:",type(x_train))

print("-"*30)
print('矩阵初值为：\n{}'.format(x_np))
print('该矩阵的均值为：{}\n该矩阵的标准差为：{}'.format(scaler.mean_,np.sqrt(scaler.var_)))
print('标准差标准化的矩阵为:\n{}'.format(x_train))

arr_np: 
 [[ 1.5 -1.   2. ]
 [ 2.   0.   0. ]]
x_np: 
      0    1    2
0  1.5 -1.0  2.0
1  2.0  0.0  0.0
y_np: 
 [[5]
 [8]]
x_train: 
 [[-1. -1.  1.]
 [ 1.  1. -1.]]
x_train and y_np: 
 [[-1. -1.  1.  5.]
 [ 1.  1. -1.  8.]]
type of x_np: <class 'numpy.ndarray'>
------------------------------
矩阵初值为：
     0    1    2
0  1.5 -1.0  2.0
1  2.0  0.0  0.0
该矩阵的均值为：[ 1.75 -0.5   1.  ]
该矩阵的标准差为：[0.25 0.5  1.  ]
标准差标准化的矩阵为:
[[-1. -1.  1.]
 [ 1.  1. -1.]]


In [2]:
dic_value={
  "peter":25,
  "jim":36,
  "jack":20
}
print(dic_value)

{'peter': 25, 'jim': 36, 'jack': 20}


In [12]:
print(dic_value)
dv=dic_value.values()
print(dv)
best=sorted(dv)

best,type(best)

{'peter': 25, 'jim': 36, 'jack': 20}
dict_values([25, 36, 20])


([20, 25, 36], list)

In [35]:
list_value=list(dic_value)
print(list_value)

['peter', 'jim', 'jack']


In [36]:
list_keys=list(dic_value.keys())
list_keys

['peter', 'jim', 'jack']

In [14]:
list_values=list(dic_value.values())
list_values

[25, 36, 20]

In [21]:
lindex=list(dic_value.values()).index(20)
lindex

2

In [22]:
name=list(dic_value.keys())[lindex]
name

'jack'